site:
  title: Example
  url: https://example.com
  start_page: en:userguide:Home.adoc
content:
  branches: HEAD
  sources:
    - url: .
      start_path: en
      version: ~
    - url: .
      start_path: fr
      version: ~
ui:
  bundle:
    url: ./node_modules/@outscale/osc-doc-framework/antora-ui/build/ui-bundle.zip
    snapshot: true
  output_dir: _
output:
  dir: ./build/site
  clean: true
runtime:
  fetch: true
antora:
  extensions:
    - require: ./node_modules/@outscale/osc-doc-framework/antora-ui
    - require: '@antora/lunr-extension'
    - require: ./node_modules/@outscale/osc-doc-framework/antora-special-pages-extension
    - require: antora-navigator-extension
    - require: ./node_modules/@outscale/osc-doc-framework/antora-extension
    - require: '@antora/collector-extension'
    - require: ./node_modules/@outscale/osc-doc-framework/antora-rss-extension
    - require: ./node_modules/@outscale/osc-doc-framework/antora-tooltipper-extension
